name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      continue-on-error: false
      with:
        toolchain: nightly
        components: clippy, rustfmt
    - run: |
        rustup --version
        cargo --version
        rustc --version
    - run: |
        cargo +nightly fmt --all -- --check
    - run: |
        cargo clippy --all --all-targets --all-features
    - run: cargo test
